### ISSUE TITLE
Managed to get a stacktrace to barf out

### ISSUE THREAD

**Issue by dkowis** [betamaxteam/betamax#130]
All of the requests actually passed, so this is something different, but it's interesting to note that there's a ResourceLeak, so it might be the right spot to look into to resolve some concurrency problems.

```
1      2014-01-30 17:52:54,519 WARN  [LittleProxy-ClientToProxyWorker-3] util.ResourceLeakDetector.? (?:?) - LEAK: ByteBuf was GC'd before being released correctly.  The following stack trace shows where the leaked object was created, rather than where you failed to release it.
io.netty.util.ResourceLeakException: io.netty.buffer.UnpooledUnsafeDirectByteBuf@25b9528e
	at io.netty.util.ResourceLeakDetector$DefaultResourceLeak.<init>(ResourceLeakDetector.java:174)
	at io.netty.util.ResourceLeakDetector.open(ResourceLeakDetector.java:116)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.<init>(UnpooledUnsafeDirectByteBuf.java:72)
	at io.netty.buffer.UnpooledByteBufAllocator.newDirectBuffer(UnpooledByteBufAllocator.java:49)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:132)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.copy(UnpooledUnsafeDirectByteBuf.java:455)
	at io.netty.buffer.AbstractByteBuf.copy(AbstractByteBuf.java:908)
	at io.netty.buffer.Unpooled.copiedBuffer(Unpooled.java:412)
	at co.freeside.betamax.proxy.netty.NettyMessageAdapter.append(NettyMessageAdapter.java:54)
	at co.freeside.betamax.proxy.BetamaxFilters.responsePre(BetamaxFilters.java:108)
	at co.freeside.betamax.proxy.netty.PredicatedHttpFilters.responsePre(PredicatedHttpFilters.java:64)
	at org.littleshoot.proxy.impl.ClientToProxyConnection.respond(ClientToProxyConnection.java:304)
	at org.littleshoot.proxy.impl.ProxyToServerConnection.respondWith(ProxyToServerConnection.java:440)
	at org.littleshoot.proxy.impl.ProxyToServerConnection.readHTTPChunk(ProxyToServerConnection.java:190)
	at org.littleshoot.proxy.impl.ProxyConnection.readHTTP(ProxyConnection.java:147)
	at org.littleshoot.proxy.impl.ProxyConnection.read(ProxyConnection.java:130)
	at org.littleshoot.proxy.impl.ProxyToServerConnection.read(ProxyToServerConnection.java:173)
	at org.littleshoot.proxy.impl.ProxyConnection.channelRead0(ProxyConnection.java:563)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:253)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at org.littleshoot.proxy.impl.ProxyConnection$ResponseReadMonitor.channelRead(ProxyConnection.java:714)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at org.littleshoot.proxy.impl.ProxyConnection$BytesReadMonitor.channelRead(ProxyConnection.java:668)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:101)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by cowboygneox** [comment]
We've upgraded our dependencies and dramatically cleaned up our usage of littleproxy in the 2.X release that is coming. Please try the new release (when it's out) and see if you can reproduce.
