### ISSUE TITLE
BetamaxHttpsSupport.configure(client) throws exception

### ISSUE THREAD

**Issue by karangb** [betamaxteam/betamax#139]
The following line ```BetamaxHttpsSupport.configure(client);``` throws the following exception:

```

java.lang.IncompatibleClassChangeError: the number of constructors during runtime and compile time for org.apache.http.conn.ssl.SSLSocketFactory do not match. Expected 12 but got 14
	at groovy.lang.MetaClassImpl.selectConstructorAndTransformArguments(MetaClassImpl.java:1410)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.selectConstructorAndTransformArguments(ScriptBytecodeAdapter.java:234)
	at co.freeside.betamax.proxy.ssl.DummySSLSocketFactory.<init>(DummySSLSocketFactory.groovy:19)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
	at co.freeside.betamax.proxy.ssl.DummySSLSocketFactory.getInstance(DummySSLSocketFactory.groovy:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1671)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3407)
	at org.codehaus.groovy.runtime.callsite.ClassMetaClassGetPropertySite.getProperty(ClassMetaClassGetPropertySite.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:227)
	at co.freeside.betamax.httpclient.BetamaxHttpsSupport.configure(BetamaxHttpsSupport.groovy:10)
	at fifa.TestFifaApp.testHighScorers(TestFifaApp.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.InvokeMethod$evaluate.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at co.freeside.betamax.Recorder$_1_evaluate_closure1.doCall(Recorder.groovy:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at co.freeside.betamax.Recorder$_1_evaluate_closure1.doCall(Recorder.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at co.freeside.betamax.Recorder.withTape(Recorder.groovy:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:78)
	at co.freeside.betamax.Recorder.this$dist$invoke$2(Recorder.groovy)
	at co.freeside.betamax.Recorder$1.methodMissing(Recorder.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:837)
	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1134)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1087)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at co.freeside.betamax.Recorder$1.evaluate(Recorder.groovy:177)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:202)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
```

**Comment by zacholauson** [comment]
I am also having this issue, are there any updates to this?

**Comment by icebrg** [comment]
My solution was to downgrade to the last version of HTTPClient with the right api (3.2.1?) and craft Java to do what Betamax was doing that complied and worked. Let me know if you want more details.

Brian

**Comment by dadoonet** [comment]
FYI: just hit the same issue with httpclient 4.3.1 which is required by Azure Java SDK. So I can't really use betamax in the azure context for now.

**Comment by 67726e** [comment]
@dadoonet So it seems like the latest release on maven central is `1.1.2` but the project does have `2.0.0-SNAPSHOT` releases available. I was able to things working using the latter snapshots which [do use the `4.3.1` release of httpclient](https://github.com/robfletcher/betamax/blob/master/betamax.gradle#L35). I did a quick write up [on my blog](http://hexcoder.us/2015/04/11/betamax-testing-with-java-8/) and have a skeleton example of using the 2.0.0 JAR with SSL and all the fun stuff. Hope that helps.

**Comment by dadoonet** [comment]
w00t! Fantastic @67726e! Testing it right now. Thanks for the link!

**Comment by roykachouh** [comment]
@67726e Thanks for the blog post! I'm not sure i follow tho. Are you able to get ssl support working? It looks like your test is expecting an exception.

* I am using the snapshots of betamax
* I forced apache client to version: `force 'org.apache.httpcomponents:httpclient:4.3.1'`
* I tried adding and removing this `BetamaxHttpsSupport.configure(restClient.client);`

All to no avail.

**Comment by 67726e** [comment]
@roykachouh I can confirm this all works correctly (capturing SSL requests) as it works both on the [sample project](https://github.com/67726e/java8-betamax/blob/master/src/test/java/us.hexcoder.java8.betamax/ExampleTest.java) I have on GitHub and because I'm using this to do integration tests with Stripe at work which _only_ operates over SSL. Also, while the gradle configuration I linked to above includes the `4.3.1` Apache HTTP lib, just generated the dependency tree for the two libs I am using `betamax-proxy` & `betamax-junit` (both `2.0-SNAPSHOT`) and neither seem to be using the library.

As a word of advice, all the documentation on this GitHub project and on the nice little website is invalid for the `2.0-SNAPSHOT`. Go off of the above sample project and what I wrote in my blogpost and that should get you up and running without a hitch.

**Comment by roykachouh** [comment]
@67726e Thanks for the help! so it turns out it really wasn't a dependency issue. I thought I would try spock, groovy for the stack of this new contract driven testing project that I am working on.

So, I was using all the groovy built in rest/http builder. Looking at your project, I noticed everything was pretty much the same, except you were using Spring's rest client to call out to an endpoint. When I was using groovy's RestClient, I had to explicitly configure it to use the proxy - with spring rest template i did not. I'm wondering if this is an issue with the underlying apache http client, wonder what the RestTemplate is using. But I will explore that another day.

For an example using groovy, spock and betamax over ssl, you can visit here

https://github.com/roykachouh/xspect

**Comment by cowboygneox** [comment]
I am 99% confident this is a dependency issue, one that will likely never be addressed on 1.x. We're working on getting all of the dependencies up-to-date on the 2.x release, so please try that out and let me know if you still have conflicts. We have been bouncing around the idea of cross-compiling if necessary, so we'll figure it out as we go.

Please reopen this if it's a problem on 2.x.
