### ISSUE TITLE
Version 1.1.2 - MissingMethodException with Groovy 2.3.3

### ISSUE THREAD

**Issue by gsaqui** [betamaxteam/betamax#141]
When recording a tape for the first time it's throwing a MissingMethodException

```
groovy.lang.MissingMethodException: No signature of method: java.util.TreeSet.sort() is applicable for argument types: (co.freeside.betamax.tape.yaml.OrderedPropertyComparator) values: [co.freeside.betamax.tape.yaml.OrderedPropertyComparator@52339045]
Possible solutions: sort(), sort(), sort(boolean), sort(groovy.lang.Closure), sort(groovy.lang.Closure), sort(boolean, groovy.lang.Closure)
	at co.freeside.betamax.tape.yaml.TapePropertyUtils.sort(TapeRepresenter.groovy:93)
	at co.freeside.betamax.tape.yaml.TapePropertyUtils.createPropertySet(TapeRepresenter.groovy:80)
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperties(PropertyUtils.java:101)
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperties(PropertyUtils.java:93)
	at org.yaml.snakeyaml.representer.Representer.getProperties(Representer.java:238)
	at co.freeside.betamax.tape.yaml.GroovyRepresenter.getProperties(GroovyRepresenter.groovy:28)
	at org.yaml.snakeyaml.representer.Representer$RepresentJavaBean.representData(Representer.java:49)
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:109)
	at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:65)
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:270)
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:261)
	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:248)
	at co.freeside.betamax.tape.yaml.YamlTape.writeTo(YamlTape.groovy:48)
	at co.freeside.betamax.tape.yaml.YamlTapeLoader.writeTape_closure2(YamlTapeLoader.groovy:56)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at co.freeside.betamax.tape.yaml.YamlTapeLoader.writeTape(YamlTapeLoader.groovy:54)
	at co.freeside.betamax.Recorder.ejectTape(Recorder.groovy:141)
	at co.freeside.betamax.Recorder.stopProxy(Recorder.groovy:205)
	at co.freeside.betamax.Recorder.withTape(Recorder.groovy:170)
	at co.freeside.betamax.Recorder$1.evaluate(Recorder.groovy:185)
```

**Comment by hvdnew** [comment]
Im getting the same issue in Java. Any updates on this issue ?

**Comment by willis7** [comment]
I've switched to Groovy 2.2.0 with Betamax version 1.1.2 and still get this error. Given the time since the last commit, I'm guessing its safe to assume this is no longer being maintained.

**Comment by cowboygneox** [comment]
To anyone having this issue, this is certainly a Groovy conflict. Please check your classpath to ensure that you are using the correct version of Groovy.

Also, the 2.x branch coming out soon won't have any dependency on Groovy, so that should solve all of these problems ONCE AND FOR ALL!!!

**Comment by gsaqui** [comment]
Looking forward to 2.0

**Comment by tonyghita** [comment]
@cowboygneox thanks for taking the reigns on this project!

**Comment by willis7** [comment]
:+1:
