### ISSUE TITLE
betamax failing with ClassNotFoundException

### ISSUE THREAD

**Issue by paolodm** [betamaxteam/betamax#151]
I am getting this:

```
Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletRegistration$Dynamic
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
```

To provide context, I am using Dropwizard framework.

**Comment by cowboygneox** [comment]
Is there a dependency conflict? It's likely your project has a dependency that conflicts with a dependency that Betamax provides. Please recreate this issue with greater details, or wait for the new version that is coming out in a month or two.
