### ISSUE TITLE
Non-deterministic java.io.IOException: Stream closed

### ISSUE THREAD

**Issue by tonyghita** [betamaxteam/betamax#152]
I'm running in to an issue where sometimes a `java.io.IOException: Stream closed` is thrown at the start of test. Usually only one test is affected out of the entire suite.

The next time the test is run, the issue disappears.

Here's the stacktrace:

```
java.io.IOException: Stream closed
    at java.util.zip.InflaterInputStream.ensureOpen(InflaterInputStream.java:67)
    at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:121)
    at java.io.FilterInputStream.read(FilterInputStream.java:83)
    at java.io.FilterInputStream.read(FilterInputStream.java:83)
    at java.security.DigestInputStream.read(DigestInputStream.java:124)
    at java.io.DataInputStream.readInt(DataInputStream.java:387)
    at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:645)
    at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:55)
    at java.security.KeyStore.load(KeyStore.java:1433)
    at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:55)
    at org.eclipse.jetty.util.ssl.SslContextFactory.getKeyStore(SslContextFactory.java:1053)
    at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1013)
    at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:264)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.server.ssl.SslSelectChannelConnector.doStart(SslSelectChannelConnector.java:612)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.server.Server.doStart(Server.java:292)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.util.component.LifeCycle$start$0.call(Unknown Source)
    at co.freeside.betamax.proxy.jetty.SimpleServer.start(SimpleServer.groovy:73)
    at co.freeside.betamax.proxy.jetty.ProxyServer.super$3$start(ProxyServer.groovy)
    at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at co.freeside.betamax.proxy.jetty.ProxyServer.start(ProxyServer.groovy:56)
    at co.freeside.betamax.HttpInterceptor$start.call(Unknown Source)
    at co.freeside.betamax.Recorder.startProxy(Recorder.groovy:198)
    at co.freeside.betamax.Recorder.this$2$startProxy(Recorder.groovy)
    at co.freeside.betamax.Recorder$this$2$startProxy.callCurrent(Unknown Source)
    at co.freeside.betamax.Recorder.withTape(Recorder.groovy:167)
```

**Comment by cowboygneox** [comment]
This is a doozy. I would expect that this is a result of a bad/expired self-signed cert. We have that fixed in 2.x, which should be coming out soon. I'll let you know when I would like you to try again.

**Comment by cowboygneox** [comment]
I think I fixed this in 2.x. Please take it for a spin and let me know.
