### ISSUE TITLE
Betamax for Android?

### ISSUE THREAD

**Issue by ifeins** [betamaxteam/betamax#157]
Is there Android support for using Betamax?
We have several tests in the code base that hit APIs and we want the tests to not rely on staging servers and would love to use a solution like Betamax.

I tried integrating betamax into project by adding the following dependencies:

```
testCompile "org.codehaus.groovy:groovy:2.4.3"
testCompile "co.freeside:betamax:1.1.2"
```

However when I try to run a test that uses a betamax tape I get the following error:

```
groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager()
    at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1723)
    at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1526)
    at org.codehaus.groovy.runtime.callsite.MetaClassConstructorSite.callConstructor(MetaClassConstructorSite.java:46)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:232)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:236)
    at co.freeside.betamax.proxy.jetty.ProxyServer.newHttpClient(ProxyServer.groovy:70)
```

It seems to conflict with the built-in `ThreadSafeClientConnManager` that is bundled in Android which doesn't have a no-arg constructor.

**Comment by juhlila** [comment]
I'd like to know that too. I tried to use betamax with my android tests but didnt succeed

**Comment by nebiros** [comment]
Any advance?, would love to see Betamax on android, <3

**Comment by alexamster** [comment]
Hit the same issue, any tips would be awesome!

**Comment by blueneogeo** [comment]
same problem here

**Comment by cowboygneox** [comment]
I don't know for sure, but I suspect that the 2.x work will function appropriately on Android due to the reduced dependencies. When we have a release, I invite Android-experts to try it out and we'll fix it if it doesn't work.

**Comment by jturolla** [comment]
any updates?

**Comment by cowboygneox** [comment]
@jturolla 2.0.1 is out, and hopefully will work with Android. However, I am not an Android developer, so I cannot verify. Would you mind trying?

**Comment by cowboygneox** [comment]
Closing due to inactivity. I see no reason that Betamax can't work with Android. Hopefully someone in the future will point out an issue if it arises.
