### ISSUE TITLE
Running JUnit Test with @FixMethodOrder(MethodSorters.NAME_ASCENDING) Causes Sequential Tests to Fail

### ISSUE THREAD

**Issue by davidwesst** [betamaxteam/betamax#160]
I've hit and resolved a strange behavior while writing JUnit tests using Java 6 and requiring a downgrade Groovy to 2.2.2 for [compatibility](https://github.com/robfletcher/betamax/issues/141).

I found that when I ran a TestClass with the @FixMethodOrder(MethodSorters.NAME_ASCENDING) annotation on the class, the first Betamax test would run, but the remaining tests would all fail with a NullPointerException (see example stack trace).

When run individually, they would run just fine and record/load tapes as expected.

To resolve the issue, I removed the @FixMethodOrder annotation and all works as expected!

I'm not sure if this is expected behavior, but being so new to the framework and Java/Groovy world in general, I figured I'd document the issue here for others, or possibly someone to explain.

---
```
java.lang.NullPointerException
	at ca.umanitoba.alma.model.AlmaUser.createFromDTO(AlmaUser.java:66)
	at ca.umanitoba.alma.AlmaRESTApiClient.getUserInfo(AlmaRESTApiClient.java:115)
	at ca.umanitoba.alma.AlmaRESTApiClientTest.getUserInfo_ShouldReturnUserWithProvidedIDIfFound(AlmaRESTApiClientTest.java:332)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.InvokeMethod$evaluate.call(Unknown Source)
	at co.freeside.betamax.Recorder$_1_evaluate_closure1.doCall(Recorder.groovy:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at co.freeside.betamax.Recorder$_1_evaluate_closure1.doCall(Recorder.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at co.freeside.betamax.Recorder.withTape(Recorder.groovy:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:78)
	at co.freeside.betamax.Recorder.this$dist$invoke$2(Recorder.groovy)
	at co.freeside.betamax.Recorder$1.methodMissing(Recorder.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:837)
	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1134)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1087)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at co.freeside.betamax.Recorder$1.evaluate(Recorder.groovy:185)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by davidwesst** [comment]
**UPDATE:** I decided to tinker with it some more, and instead of using the Rule annotation as suggested in the [usage](http://freeside.co/betamax/#usage) of the documentation, I replaced with with an explicit setup and teardown methods (```@Before``` and ```@After```) where I initialize and null the recorder (see below) and the tests now work with the ```@FixMethodOrder``` annotation! 

Success! Although, would still like to know what is going on, but it's likely more of a JUnit thing rather than a Betamax thing.

```
	public Recorder recorder;
	
	@Before
	public void setUp() {
		recorder = new Recorder();
	}
	
	@After
	public void tearDown() {
		recorder = null;
	}
```

**Comment by davidwesst** [comment]
**ANOTHER UPDATE:** It appears that I hit another snag with my solution. 

After adding more tests, Betamax stopped recording traffic. Not sure why, but returning the ```@Rule``` annotation and removing the ```@FixMethodOrder(MethodSorters.NAME_ASCENDING)``` seemed to resolve the problem. 

I'm convinced it has something to do with the way I have the dependencies setup as per my previous comment, but for now I have a workaround.

**Comment by cowboygneox** [comment]
@davidwesst I apologize for the issues you have been experiencing. Hopefully the 2.x refactor will make Betamax much easier to use. I would be interested in seeing if this works on the current master. Do you have time to submit a test that asserts this behavior is working (or not working)?

**Comment by cowboygneox** [comment]
@davidwesst I'm going to close this due to inactivity. Please feel free to reopen if you would like.
