### ISSUE TITLE
Betamax needs to be forked

### ISSUE THREAD

**Issue by rschmitt** [betamaxteam/betamax#167]
Since this project is clearly no longer maintained, someone will need to commit to forking it so that development can continue. Any volunteers?

**Comment by cowboygneox** [comment]
I can take it over, but I'll want to refactor the Groovy dependency out of it. I'll fork it right now, and if someone wants me to work on it, please be sure to create issues/requests/comments.

**Comment by cowboygneox** [comment]
https://github.com/cowboygneox/betamax

**Comment by rschmitt** [comment]
Thanks for volunteering!

> I can take it over, but I'll want to refactor the Groovy dependency out of it.

Interesting, isn't the Groovy dependency just for tests?

**Comment by cowboygneox** [comment]
Yes but I just tried it with a version newer than 2.2.0 and it threw a fit. Plus, Groovy dependencies on libraries like this make it a potential conflict for those with Groovy already, even in their tests, and it discourages developers who do not like the "swiss army knife" that is Groovy in their classpath at all.

Plus, personally, I think it's easier to develop and test a nice, clean, simple library in Java. I'm a Scala guy myself, but my perfect idea of an open source library is as few dependencies as possible. I'm likely going to split this into multiple libraries so devs can pick what they choose (in my case, I would like a Specs2 variant for Scala, but as something like `betamax-specs2` that depends on `betamax-core`, or something like that.

**Comment by cowboygneox** [comment]
@rschmitt Also, if you mean "just for tests" meaning for the tests of this library, that is not true; betamax 1.1.2 requires Groovy in the classpath to function.

**Comment by rschmitt** [comment]
Just for curiosity, can you paste the output of Groovy's tantrum?

**Comment by cowboygneox** [comment]
Example stack from my specs2 experiment:

```
groovy.lang.MissingMethodException: No signature of method: java.util.TreeSet.sort() is applicable for argument types: (co.freeside.betamax.tape.yaml.OrderedPropertyComparator) values: [co.freeside.betamax.tape.yaml.OrderedPropertyComparator@51ec220e]
Possible solutions: sort(), sort(), sort(boolean), sort(groovy.lang.Closure), sort(boolean, java.util.Comparator), sort(boolean, groovy.lang.Closure)
groovy.lang.MissingMethodException: No signature of method: java.util.TreeSet.sort() is applicable for argument types: (co.freeside.betamax.tape.yaml.OrderedPropertyComparator) values: [co.freeside.betamax.tape.yaml.OrderedPropertyComparator@51ec220e]
Possible solutions: sort(), sort(), sort(boolean), sort(groovy.lang.Closure), sort(boolean, java.util.Comparator), sort(boolean, groovy.lang.Closure)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:49)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at co.freeside.betamax.tape.yaml.TapePropertyUtils.sort(TapeRepresenter.groovy:93)
	at co.freeside.betamax.tape.yaml.TapePropertyUtils.this$3$sort(TapeRepresenter.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
	at co.freeside.betamax.tape.yaml.TapePropertyUtils.createPropertySet(TapeRepresenter.groovy:80)
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperties(PropertyUtils.java:101)
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperties(PropertyUtils.java:93)
	at org.yaml.snakeyaml.representer.Representer.getProperties(Representer.java:238)
	at co.freeside.betamax.tape.yaml.GroovyRepresenter.super$4$getProperties(GroovyRepresenter.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:132)
	at co.freeside.betamax.tape.yaml.GroovyRepresenter.getProperties(GroovyRepresenter.groovy:28)
	at org.yaml.snakeyaml.representer.Representer$RepresentJavaBean.representData(Representer.java:49)
	at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:109)
	at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:65)
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:270)
	at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:261)
	at org.yaml.snakeyaml.Yaml.dump(Yaml.java:248)
	at org.yaml.snakeyaml.Yaml$dump.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at co.freeside.betamax.tape.yaml.YamlTape.writeTo(YamlTape.groovy:48)
	at co.freeside.betamax.tape.StorableTape$writeTo$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at co.freeside.betamax.tape.yaml.YamlTapeLoader$_writeTape_closure2.doCall(YamlTapeLoader.groovy:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:442)
	at org.codehaus.groovy.runtime.IOGroovyMethods.withWriter(IOGroovyMethods.java:1155)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.withWriter(ResourceGroovyMethods.java:1843)
	at org.codehaus.groovy.runtime.dgm$1032.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at co.freeside.betamax.tape.yaml.YamlTapeLoader.writeTape(YamlTapeLoader.groovy:54)
	at co.freeside.betamax.tape.TapeLoader$writeTape$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at co.freeside.betamax.Recorder.ejectTape(Recorder.groovy:141)
	at com.gneoxsolutions.dock99.boats.net.Betamax$class.withTape(Betamax.scala:26)
	at com.gneoxsolutions.dock99.boats.net.GoogleBetamaxSpec.withTape(GoogleBetamaxSpec.scala:10)
	at com.gneoxsolutions.dock99.boats.net.GoogleBetamaxSpec$$anonfun$1$$anonfun$apply$3.apply(GoogleBetamaxSpec.scala:12)
	at com.gneoxsolutions.dock99.boats.net.GoogleBetamaxSpec$$anonfun$1$$anonfun$apply$3.apply(GoogleBetamaxSpec.scala:12)
	at org.specs2.matcher.MatchResult$$anon$12$$anonfun$asResult$1.apply(MatchResult.scala:343)
	at org.specs2.matcher.MatchResult$$anon$12$$anonfun$asResult$1.apply(MatchResult.scala:343)
	at org.specs2.execute.ResultExecution$class.execute(ResultExecution.scala:23)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:118)
	at org.specs2.execute.Result$$anon$10.asResult(Result.scala:227)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:25)
	at org.specs2.matcher.MatchResult$$anon$12.asResult(MatchResult.scala:343)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:25)
	at org.specs2.main.CommandLineAsResult$$anon$1.asResult(CommandLineAsResult.scala:17)
	at org.specs2.main.CommandLineAsResult$$anonfun$apply$1.apply(CommandLineAsResult.scala:21)
	at org.specs2.main.CommandLineAsResult$$anonfun$apply$1.apply(CommandLineAsResult.scala:21)
	at org.specs2.specification.dsl.mutable.ExampleDsl1$BlockExample$$anonfun$$greater$greater$1.apply(ExampleDsl.scala:39)
	at org.specs2.specification.dsl.mutable.ExampleDsl1$BlockExample$$anonfun$$greater$greater$1.apply(ExampleDsl.scala:39)
	at org.specs2.specification.core.Execution$$anonfun$withEnv$1$$anonfun$apply$5.apply(Execution.scala:132)
	at org.specs2.execute.ResultExecution$class.execute(ResultExecution.scala:23)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:118)
	at org.specs2.execute.Result$$anon$10.asResult(Result.scala:227)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:25)
	at org.specs2.specification.core.Execution$$anonfun$withEnv$1.apply(Execution.scala:132)
	at org.specs2.specification.core.Execution$$anonfun$withEnv$1.apply(Execution.scala:132)
	at org.specs2.specification.core.Execution$$anonfun$execute$2$$anonfun$apply$4.apply(Execution.scala:73)
	at org.specs2.specification.core.Execution$$anonfun$execute$2$$anonfun$apply$4.apply(Execution.scala:73)
	at org.specs2.specification.core.Execution.setResult(Execution.scala:81)
	at org.specs2.specification.core.Execution$$anonfun$execute$2.apply(Execution.scala:73)
	at org.specs2.specification.core.Execution$$anonfun$execute$2.apply(Execution.scala:72)
	at scala.Option.fold(Option.scala:158)
	at org.specs2.specification.core.Execution.execute(Execution.scala:72)
	at org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1$$anonfun$apply$16.apply(Executor.scala:150)
	at org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1$$anonfun$apply$16.apply(Executor.scala:148)
	at org.specs2.specification.core.Fragment.updateExecution(Fragment.scala:49)
	at org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1.apply(Executor.scala:148)
	at org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1.apply(Executor.scala:147)
	at org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1$$anonfun$9.apply(Executor.scala:135)
	at org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1$$anonfun$9.apply(Executor.scala:135)
	at scalaz.concurrent.Task$.Try(Task.scala:446)
	at org.specs2.data.Processes$$anonfun$start$1.apply(Processes.scala:115)
	at org.specs2.data.Processes$$anonfun$start$1.apply(Processes.scala:115)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:433)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:433)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rschmitt** [comment]
And the output of `java -version`?

**Comment by cowboygneox** [comment]
@rschmitt 

```
$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

**Comment by rschmitt** [comment]
Well, what do you know, Betamax's extensive backlog of patches contains a fix for this exact problem:

https://github.com/robfletcher/betamax/issues/141

Apparently, you have to add a `false` to that method call as the first argument.

**Comment by cowboygneox** [comment]
@rschmitt I'll start bringing those over. Feel free to migrate it for me if you want to, because I can't do it today :)

**Comment by robfletcher** [comment]
Hey guys sorry I didn't see this thread earlier. Groovy is no longer a dependency for the code that exists in master. I just never got it quite as far as releasing it. I can only apologize for not paying much attention to this project – life kind of got in the way.

**Comment by cowboygneox** [comment]
@robfletcher I tried to email you, but I have been doing a ton of work on my fork reviving this project. Please reach put to me to see if you're interested in collaborating.

**Comment by cowboygneox** [comment]
@robfletcher and I have teamed up and are reviving this project. Expect a new version very soon. Closing...
