### ISSUE TITLE
SSL support may not be working

### ISSUE THREAD

**Issue by pledbrook** [betamaxteam/betamax#189]
I have Betamax proxying a bunch of SSL requests, which were working with 1.1.2. Now I'm getting the following error with the alpha-1 release of 2.0:

```
Caused by: java.security.cert.CertificateException: No name matching bintray.com found
    at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:221)
```

I'm not sure what the intended behaviour is for Betamax. Dynamically creating the certificate for the requested domain? Or creating a 'catch-all' certificate in which the domain doesn't matter? I'm not even sure the latter is possible.

Anyway, I really don't know if this is a bug, or I need to adjust my Betamax configuration somehow.

**Comment by pledbrook** [comment]
On the Betamax side, the error looks like this:

    SEVERE: (NEGOTIATING_CONNECT) [id: 0x78c6897e, /192.168.1.104:55491 :> 0.0.0.0/0.0.0.0:5555]: Caught an exception on ClientToProxyConnection
    io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
    	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:280)
    	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
    	at     io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
    	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
    	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
    	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
    	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634)
    	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800)
    	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083)
    	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
    	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
    	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
    	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:982)
    	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:908)
    	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:854)
    	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
    	... 11 more

**Comment by pledbrook** [comment]
It looks like SSL certificate spoofing isn't implemented directly in LittleProxy right now. That's at least what I infer from [this LittleProxy issue](https://github.com/adamfisk/LittleProxy/issues/184). That discussion thread does point at a couple of (non-standard) options to do what we want. There is also an [outstanding pull request](https://github.com/adamfisk/LittleProxy/pull/230) that probably has what we need.

**Comment by cowboygneox** [comment]
@pledbrook As of right now, you have to disable hostname checking on your client. We have a number of examples of how to do that with apache httpclient. We may not be able to do this automatically, but I'll keep looking into a means to do this; it probably means we'll have to generate certs as necessary, but that's a generous scope increase.

**Comment by pledbrook** [comment]
@cowboygneox Isn't that what 1.1.x is already doing though, generating certificates with the correct host name? I don't see how else it's working for me but 2.x is not. That's why I was interested in Rob's input as he may be able to explain what's different between the versions with respect to this issue.

**Comment by cowboygneox** [comment]
@pledbrook I haven't sat down and done all of the research to conclude one way or another, but I don't think the original betamax used a proxy; I think it was more like VCR in that it just altered the behavior of a given client. The refactor to use an actual proxy (aka littleproxy) was part of the 2.0 initiative, and introduced its own complications, especially with Java 7/8 enforcing use of the truststore even more.

@pledbrook Please ensure that hostnameVerification is disabled on your client and try again.

**Comment by cowboygneox** [comment]
@pledbrook Can you try this with the most recent SNAPSHOT? The instructions for configuring SSL are in the README.

**Comment by cowboygneox** [comment]
Closing due to lack of activity. SSL support is working within the project. Hopefully it's enough as is...
