### ISSUE TITLE
Start jetty in external process

### ISSUE THREAD

**Issue by hgoebl** [betamaxteam/betamax#51]
We have very nasty problems using Betamax with Java/Glassfish/Jersey

```
		<dependency>
			<groupId>org.glassfish.extras</groupId>
			<artifactId>glassfish-embedded-all</artifactId>
			<version>3.1.1</version>
			<scope>test</scope>
		</dependency>
```

The problem: jetty-server uses SLF4J 1.6.x and the fat pig glassfish-embedded-all carries SLF4J 1.5.6.

```
java.lang.NoSuchMethodError: org.slf4j.spi.LocationAwareLogger.log(Lorg/slf4j/Marker;Ljava/lang/String;ILjava/lang/String;[Ljava/lang/Object;Ljava/lang/Throwable;)
        at org.eclipse.jetty.util.log.JettyAwareLogger.log(JettyAwareLogger.java:591)
        at org.eclipse.jetty.util.log.JettyAwareLogger.debug(JettyAwareLogger.java:193)
        at org.eclipse.jetty.util.log.Slf4jLog.debug(Slf4jLog.java:92)
        at org.eclipse.jetty.util.log.Log.initialized(Log.java:80)
        at org.eclipse.jetty.util.log.Log.getLogger(Log.java:357)
        at org.eclipse.jetty.util.log.Log.getLogger(Log.java:347)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.<clinit>(AbstractLifeCycle.java:28)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:169)
        at betamax.proxy.jetty.ProxyServer.class$(ProxyServer.groovy)
        at betamax.proxy.jetty.ProxyServer.$get$$class$betamax$proxy$jetty$ProxyHandler(ProxyServer.groovy)
        at betamax.proxy.jetty.ProxyServer.start(ProxyServer.groovy:30)
```

I tried to change the order of dependencies but didn't find a solution.
A patched version of glassfish-embedded-all w/o SLF4J didn't work either.

Would it be possible to start jetty in an external process?

**Comment by cowboygneox** [comment]
I apologize that this has gone for so long overlooked. We currently do not have plans to support running Betamax in a forked process. Our most recent efforts have been to simplify, refactor, and reduce dependencies. I would say a fork is a natural evolution as long as we can get it to play nice with Maven, but we're still a ways out from that.

If you're still interested, we should discuss a feature request and build some acceptance criteria.
