### ISSUE TITLE
Handling of bad/corrupt tape files could be better

### ISSUE THREAD

**Issue by berinle** [betamaxteam/betamax#81]
When a bad tape exists, betamax panics with the error below. 

java.lang.NullPointerException: Cannot invoke method size() on null object
    at co.freeside.betamax.tape.yaml.YamlTapeLoader.loadTape(YamlTapeLoader.groovy:43)
    at co.freeside.betamax.Recorder.insertTape(Recorder.groovy:121)
    at co.freeside.betamax.Recorder.startProxy(Recorder.groovy:200)
    at co.freeside.betamax.Recorder.withTape(Recorder.groovy:167)
    at co.freeside.betamax.Recorder$1.evaluate(Recorder.groovy:185)
    at org.spockframework.runtime.extension.builtin.MethodRuleInterceptor.intercept(MethodRuleInterceptor.java:40)
    at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:84)
    at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:138)
    at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:138)
    at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:138)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)

**Comment by cowboygneox** [comment]
Moved to Trello: https://trello.com/c/GGBtvEAv
