### ISSUE TITLE
UnknownHostException resolving local host name kills Proxy

### ISSUE THREAD

**Issue by mahileeb** [betamaxteam/betamax#82]
When running tests on our build slaves where the local host name cannot be resolved, our tests fail due to an UnknownHostException in the ProxyServer constructor:

java.net.UnknownHostException: ip-10-10-1-151: ip-10-10-1-151
    at java.net.InetAddress.getLocalHost(InetAddress.java:1360)
...
    at co.freeside.betamax.proxy.jetty.SimpleServer.<init>(SimpleServer.groovy:46)
    at co.freeside.betamax.proxy.jetty.ProxyServer.<init>(ProxyServer.groovy:40)
        at co.freeside.betamax.Recorder.<init>(Recorder.groovy:109)

**Comment by cowboygneox** [comment]
I don't think this is an issue on 2.x. Closing...
