### ISSUE TITLE
Out of memory errors when running on build server

### ISSUE THREAD

**Issue by berinle** [betamaxteam/betamax#83]
Running betamax via maven on our build servers is causing outofmemory errors, even after increasing the heap and permgen sizes.

Currently running with this setting JVM arg settings:
-Xmx1536m -XX:MaxPermSize=2048m

     13:35:04,996 DEBUG [org.eclipse.jetty.util.log] Container org.eclipse.jetty.     server.Server@69210267 + SslSelectChannelConnector@0.0.0.0:5556 as connector
     13:35:04,996 DEBUG [org.eclipse.jetty.util.log] Container org.eclipse.jetty.     server.Server@69210267 + co.freeside.betamax.proxy.jetty.     CustomConnectHandler@180c20e9 as handler
     13:35:04,996 DEBUG [org.eclipse.jetty.util.log] Container co.freeside.betamax     .proxy.jetty.CustomConnectHandler@180c20e9 + co.freeside.betamax.proxy.jetty.     BetamaxProxy@4444ad54 as handler
     13:35:04,997 DEBUG [org.eclipse.jetty.util.log] Container co.freeside.betamax     .proxy.jetty.CustomConnectHandler@180c20e9 + org.eclipse.jetty.server.handler     .ConnectHandler$Manager@78cf88cf as selectManager
     13:35:05,000 DEBUG [org.eclipse.jetty.util.log] Starting org.eclipse.jetty.     server.Server@69210267
     13:35:05,000 INFO  [org.eclipse.jetty.util.log] jetty-7.3.1.v20110307
     13:35:05,028 DEBUG [org.eclipse.jetty.util.log] Container org.eclipse.jetty.     server.Server@69210267 + qtp318675530{8<=0<=0/254,-1} as threadpool
     13:35:05,029 DEBUG [org.eclipse.jetty.util.log] Starting co.freeside.betamax.     proxy.jetty.CustomConnectHandler@180c20e9
     13:35:05,029 DEBUG [org.eclipse.jetty.util.log] Starting co.freeside.betamax.     proxy.jetty.BetamaxProxy@4444ad54
     13:35:05,029 DEBUG [org.eclipse.jetty.util.log] starting co.freeside.betamax.     proxy.jetty.BetamaxProxy@4444ad54
     13:35:05,029 DEBUG [org.eclipse.jetty.util.log] STARTED co.freeside.betamax.     proxy.jetty.BetamaxProxy@4444ad54
     13:35:05,030 DEBUG [org.eclipse.jetty.util.log] starting co.freeside.betamax.     proxy.jetty.CustomConnectHandler@180c20e9
     13:35:05,030 DEBUG [org.eclipse.jetty.util.log] Starting      qtp318675530{8<=0<=0/254,-1}
     13:35:05,033 DEBUG [org.eclipse.jetty.util.log] STARTED      qtp318675530{8<=3<=8/254,0}
     13:35:05,033 DEBUG [org.eclipse.jetty.util.log] Starting org.eclipse.jetty.     server.handler.ConnectHandler$Manager@78cf88cf
     13:35:05,053 DEBUG [org.eclipse.jetty.util.log] STARTED org.eclipse.jetty.     server.handler.ConnectHandler$Manager@78cf88cf
     13:35:05,054 DEBUG [org.eclipse.jetty.util.log] STARTED co.freeside.betamax.     proxy.jetty.CustomConnectHandler@180c20e9
     13:35:05,054 DEBUG [org.eclipse.jetty.util.log] starting org.eclipse.jetty.     server.Server@69210267
     13:35:05,054 DEBUG [org.eclipse.jetty.util.log] Starting      SelectChannelConnector@0.0.0.0:5555
     13:35:05,054 DEBUG [org.eclipse.jetty.util.log] Starting org.eclipse.jetty.     server.nio.SelectChannelConnector$ConnectorSelectorManager@72aad957
     13:35:05,055 DEBUG [org.eclipse.jetty.util.log] STARTED org.eclipse.jetty.     server.nio.SelectChannelConnector$ConnectorSelectorManager@72aad957
     13:35:05,058 INFO  [org.eclipse.jetty.util.log] Started      SelectChannelConnector@0.0.0.0:5555
     13:35:05,059 DEBUG [org.eclipse.jetty.util.log] STARTED      SelectChannelConnector@0.0.0.0:5555
     13:35:05,059 DEBUG [org.eclipse.jetty.util.log] Starting      SslSelectChannelConnector@0.0.0.0:5556
     13:35:05,059 DEBUG [org.eclipse.jetty.util.log] Starting org.eclipse.jetty.     http.ssl.SslContextFactory@4edddc70
     13:35:05,079 DEBUG [org.eclipse.jetty.util.log] STARTED org.eclipse.jetty.     http.ssl.SslContextFactory@4edddc70
     13:35:06,261 WARN  [org.eclipse.jetty.util.log] FAILED      SslSelectChannelConnector@0.0.0.0:5556: java.lang.OutOfMemoryError: PermGen      space
     13:35:06,262 DEBUG [org.eclipse.jetty.util.log] EXCEPTION 
     java.lang.OutOfMemoryError: PermGen space
     	at com.sun.net.ssl.internal.ssl.SSLEngineImpl.init(SSLEngineImpl.     java:342)
     	at com.sun.net.ssl.internal.ssl.SSLEngineImpl.<init>(SSLEngineImpl.     java:306)
     	at com.sun.net.ssl.internal.ssl.SSLContextImpl.engineCreateSSLEngine(     SSLContextImpl.java:163)
     	at javax.net.ssl.SSLContext.createSSLEngine(SSLContext.java:295)
     	at org.eclipse.jetty.server.ssl.SslSelectChannelConnector.doStart(     SslSelectChannelConnector.java:601)
     	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(     AbstractLifeCycle.java:55)
     	at org.eclipse.jetty.server.Server.doStart(Server.java:269)
     	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(     AbstractLifeCycle.java:55)
     	at org.eclipse.jetty.util.component.LifeCycle$start.call(Unknown Source)
     	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(     CallSiteArray.java:45)
     	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(     AbstractCallSite.java:108)
     	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(     AbstractCallSite.java:112)
     	at co.freeside.betamax.proxy.jetty.SimpleServer.start(SimpleServer.     groovy:73)
     	at co.freeside.betamax.proxy.jetty.ProxyServer.super$3$start(ProxyServer.     groovy)
     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.     java:39)
     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(     DelegatingMethodAccessorImpl.java:25)
     	at java.lang.reflect.Method.invoke(Method.java:597)
     	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.     java:90)
     	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
     	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1076)
     	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN     (ScriptBytecodeAdapter.java:128)
     	at co.freeside.betamax.proxy.jetty.ProxyServer.start(ProxyServer.     groovy:56)
     	at co.freeside.betamax.HttpInterceptor$start.call(Unknown Source)
     	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(     CallSiteArray.java:45)
     	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(     AbstractCallSite.java:108)
     	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(     AbstractCallSite.java:112)
     	at co.freeside.betamax.Recorder.startProxy(Recorder.groovy:198)
     	at co.freeside.betamax.Recorder.this$2$startProxy(Recorder.groovy)
     	at co.freeside.betamax.Recorder$this$2$startProxy.callCurrent(Unknown      Source)
     	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(     CallSiteArray.java:49)
     	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(     AbstractCallSite.java:133)
     13:35:06,786 WARN  [org.eclipse.jetty.util.log] FAILED org.eclipse.jetty.     server.Server@69210267: java.lang.OutOfMemoryError: PermGen space

**Comment by cowboygneox** [comment]
I don't believe this is a relevant issue anymore due to the fact that we are using Netty and not Jetty. We'll keep an eye out for memory issues going forward.
