### ISSUE TITLE
Cannot intercept ssl traffic in grails tests

### ISSUE THREAD

**Issue by EchelonFour** [betamaxteam/betamax#90]
When writing tests that need to tape ssl traffic in grails, Betamax always causes the test to fail.
The following test:
```
@Rule Recorder recorder = new Recorder(sslSupport:true)

@Betamax(tape='tape')
void "test google tape"() {
    when:
    def google = new URL('https://google.com').text
    then:
    google.contains("I'm Feeling Lucky")
}
```
causes the following exception
```
| Failure:  test google tape(TestBetamaxSpec)
|  java.net.SocketException: java.lang.ClassNotFoundException: co.freeside.betamax.ssl.DummyJVMSSLSocketFactory
	at javax.net.ssl.DefaultSSLSocketFactory.throwException(SSLSocketFactory.java:198)
	at javax.net.ssl.DefaultSSLSocketFactory.createSocket(SSLSocketFactory.java:218)
	at TestBetamaxSpec.test google tape(TestBetamaxSpec.groovy:24)
Caused by: java.lang.ClassNotFoundException: co.freeside.betamax.ssl.DummyJVMSSLSocketFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:104)
	at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:333)
	at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:291)
	at java.net.URL.openConnection(URL.java:971)
```
I assume this is because of how the grails classloader works.
This is with Grails 2.2.3

**Comment by cowboygneox** [comment]
I would expect this is not something we're going to fix in the 1.x version, but this should be functional in th e coming 2.x version. Please reopen if this is not the case.
